// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymwzgxfecrvwzydjoohl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inltd3pneGZlY3J2d3p5ZGpvb2hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzQ4NjIsImV4cCI6MjA2MTI1MDg2Mn0.Qp6ALz6vvQg-yy0fqFcMqXnu_2JCOON1T-_tHcGA0-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);